spring.application.name=IDOIT

# JSP 설정
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Oracle 설정
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xe
spring.datasource.username=scott
spring.datasource.password=tiger

# MyBatis 설정
mybatis.mapper-locations=classpath:mybatis/mapper/**/**.xml

# Elasticsearch 설정
spring.elasticsearch.uris=http://localhost:9200

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

# ===============================
# Kakao OAuth2 Login
# ===============================

spring.security.oauth2.client.registration.kakao.client-id=6c3a9b7ce5cfd924715e1871bd609209
spring.security.oauth2.client.registration.kakao.client-secret=nLDo2fO1jQ51BVLBMF5uU2vvU1yqGecE
spring.security.oauth2.client.registration.kakao.client-authentication-method=client_secret_post
spring.security.oauth2.client.registration.kakao.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.kakao.redirect-uri={baseUrl}/login/oauth2/code/kakao
spring.security.oauth2.client.registration.kakao.scope=profile_nickname,profile_image
spring.security.oauth2.client.provider.kakao.authorization-uri=https://kauth.kakao.com/oauth/authorize
spring.security.oauth2.client.provider.kakao.token-uri=https://kauth.kakao.com/oauth/token
spring.security.oauth2.client.provider.kakao.user-info-uri=https://kapi.kakao.com/v2/user/me
spring.security.oauth2.client.provider.kakao.user-name-attribute=id

logging.level.com.idoit=DEBUG

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB